version: '3.3'
services:
    db:
        image: 'mysql:8.0.26'
        container_name: mysql-catalog
        restart: always
        ports:
          - '3306:3306'
        environment:
          - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
          - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
          - 'MYSQL_USER=${MYSQL_USER}'
          - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
        cap_add:
          - 'SYS_NICE'
        volumes:
          - './mysql/_data:/var/lib/mysql'
        networks:
          - proxy

    discovery-server:
        container_name: eureka-server
        image: discovery-server:v0.1
        build:
          context: .
          args: 
            JAR_FILE: discovery-server-0.0.1-SNAPSHOT
            PARENT_FOLDER: discovery-server
        environment:
          - "JAVA_OPTS=-XX:MinRAMPercentage=20 -XX:MaxRAMPercentage=70"
        ports:
            - "8761:8761"
        networks:
          - proxy
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"
            
    movie-catalog-service:
        container_name: catalog-microservice
        image: movie-catalog-service:v0.1
        build:
          context: .
          args: 
            JAR_FILE: movie-catalog-service-0.0.1-SNAPSHOT
            PARENT_FOLDER: movie-catalog-service
        environment:
          - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka"
          - "JAVA_OPTS=-XX:MinRAMPercentage=20 -XX:MaxRAMPercentage=70"
        ports:
            - "8081:8081"
        depends_on:
          - movie-service
          - rating-service
          - discovery-server
        links:
          - discovery-server
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.movie-catalog-service.rule=Host(`catalog.docker.localhost`)"
          - "traefik.http.routers.movie-catalog-service.tls=true"
          - "traefik.http.services.movie-catalog-service.loadbalancer.server.port=8081"
          - "collect_logs_with_filebeat=true"
          - "decode_log_event_to_json_object=true"
        networks:
          - proxy
    
    movie-service:
        container_name: movie-microservice
        image: movie-service:v0.1
        build:
          context: .
          args: 
            JAR_FILE: movie-service-0.0.1-SNAPSHOT
            PARENT_FOLDER: movie-service
        environment:
          - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
          - spring.datasource.url=jdbc:mysql://db/catalog
          - "JAVA_OPTS=-XX:MinRAMPercentage=20 -XX:MaxRAMPercentage=70"
        ports:
            - "8082:8082"
        depends_on:
          - discovery-server
          - db
        links:
          - discovery-server
        networks:
          - proxy
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"

    rating-service:
        container_name: rating-microservice
        image: rating-service:v0.1
        build:
          context: .
          args: 
            JAR_FILE: rating-service-0.0.1-SNAPSHOT
            PARENT_FOLDER: rating-service
        environment:
          - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
          - spring.datasource.url=jdbc:mysql://db/catalog
          - "JAVA_OPTS=-XX:MinRAMPercentage=20 -XX:MaxRAMPercentage=70"
        ports:
            - "8083:8083"
        depends_on:
          - discovery-server
          - db
        links:
          - discovery-server
        networks:
          - proxy
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"
      
networks:
  proxy:
    external: true