version: '3.3'
services:
    db:
        image: 'mysql:8.0.26'
        container_name: mysql-catalog
        restart: always
        ports:
          - '3306:3306'
        environment:
          - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
          - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
          - 'MYSQL_USER=${MYSQL_USER}'
          - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
        cap_add:
          - 'SYS_NICE'
        volumes:
          - './mysql/_data:/var/lib/mysql'
        networks:
          - proxy

    discovery-server:
        container_name: eureka-server
        image: discovery-server:v0.1
        build:
          context: .
          args: 
            JAR_FILE: discovery-server-0.0.1-SNAPSHOT
            PARENT_FOLDER: discovery-server
        environment:
          - "JAVA_OPTS=-XX:MinRAMPercentage=20 -XX:MaxRAMPercentage=70"
        ports:
            - "8761:8761"
        networks:
          - proxy
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"
    
networks:
  proxy:
    external: true