version: '3.3'
services:

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
        - "9090:9090"
    networks:
        - proxy
    volumes:
        - ./prometheus/:/etc/prometheus/
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:8.2.2
    ports:
        - "3000:3000"
    networks:
        - proxy
    volumes:
        - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
        - prometheus

networks:
  proxy:
    external: true