server:
  port: 8081

spring:
  application:
    name: "movie-catalog-service"
  cloud:
    config:
      retry:
        initial-interval: 1500
        multiplier: 1.5
        max-attempts: 10000
        max-interval: 1000

eureka:
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
  client:
    region: default
    availability-zones:
      default: default-zone
    serviceUrl:
      registerWithEureka: true
      fetchRegistry: true
      registryFetchIntervalSeconds: 5
      defaultZone: http://discovery-server:8761/eureka/

feign:
  client:
    config:
      connectTimeout: 5000
      readTimeout: 5000
      loggerLevel: basic

management:
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
