spring:
  application:
    name: "discovery.server"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761 #Default Eureka Server port

management:
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"