global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'catalog'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'movie-catalog-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['movie-catalog-service:8081']