global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'catalog'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'movie-catalog-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['movie-catalog-service:8081']

  - job_name: 'movie-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['movie-service:8082']

  - job_name: 'rating-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['rating-service:8083']