server:
  port: 8082

spring:
  application:
    name: "movie-service"
  cloud:
    config:
      retry:
        initial-interval: 1500
        multiplier: 1.5
        max-attempts: 10000
        max-interval: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka